blank_issues_enabled: true
contact_links:
  - name: Volunteer contributors
    url: https://github.com/rottitime/govuk-design-react/blob/main/VOLUNTEERS.md
    about: Interested in contributing? See how you can help.
